environment_config:
  path: environment_config.dart

  fields:
    twitterConsumerApiKey:
      type: String
      env_var: TWITTER_CONSUMER_API_KEY
    twitterConsumerSecret:
      type: String
      env_var: TWITTER_CONSUMER_SECRET
    twitterRedirectUri:
      type: String
      env_var: TWITTER_REDIRECT_URI
    revenueCatPublicAppleApiKey:
      type: String
      env_var: REVENUE_CAT_PUBLIC_APPLE_API_KEY
    revenueCatPublicGoogleApiKey:
      type: String
      env_var: REVENUE_CAT_PUBLIC_GOOGLE_API_KEY
    serverHostForEmulatorConfiguration:
      type: String
      env_var: SERVER_HOST_FOR_EMULATOR_CONFIGURATION
