name: CI/API

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "task/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    # Use the same version of the environment on which the production runtime is based.
    # https://cloud.google.com/functions/docs/reference/system-packages#ubuntu_1804
    runs-on: ubuntu-18.04

    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - uses: actions/checkout@v3

      - name: Test API
        uses: ./.github/actions/test-api
        with:
          api-test-sample-movies-zip-url: ${{ secrets.API_TEST_SAMPLE_MOVIES_ZIP_URL }}
