name: CI/API

on:
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: "3.9"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    # Use the same version of the environment on which the production runtime is based.
    # https://cloud.google.com/functions/docs/reference/system-packages#ubuntu_1804
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          sudo apt-get install ffmpeg
          ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        working-directory: task
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download test samples
        env:
          API_TEST_SAMPLE_MOVIES_ZIP_URL: ${{ secrets.API_TEST_SAMPLE_MOVIES_ZIP_URL }}
        working-directory: task
        run: |
          mkdir samples
          cd samples
          wget -O samples.zip "${API_TEST_SAMPLE_MOVIES_ZIP_URL}"
          unzip samples.zip

      - name: Test
        working-directory: task
        run: pytest
