name: CI/API(dependabot)

on:
  pull_request_target:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test API
    # Use the different version of the environment on which the production runtime is based.
    # This is because upgrading the runtime version of Cloud Functions causes 
    # deployment failures, and GitHub Actions has already deprecated ubuntu 18.04.
    runs-on: ubuntu-22.04
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - uses: actions/checkout@v3
        with:
          # Specify PR head commit
          # because the difference may not be reflected on the default merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Test API
        uses: ./.github/actions/test-api
        with:
          api-test-sample-movies-zip-url: ${{ secrets.API_TEST_SAMPLE_MOVIES_ZIP_URL }}
